# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metagraf < Formula
  desc ""
  homepage ""
  version "0.1.51"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terbolous/metagraf/releases/download/v0.1.51/mg-0.1.51-darwin-amd64.tar.gz"
      sha256 "2b84b70b59a44f81deac6554bc5fa4442090b2f8bc14f0b70a583404b3788820"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/terbolous/metagraf/releases/download/v0.1.51/mg-0.1.51-linux-amd64.tar.gz"
      sha256 "0c8e32fc9f114849bc4fb8bc5c615c98489f549699c57d9110560ec009e2df8b"
    end
  end

  def install
    bin.install "mg"
  end
end
