# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Metagraf < Formula
  desc ""
  homepage ""
  version "0.1.54"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/terbolous/metagraf/releases/download/v0.1.54/mg-0.1.54-darwin-amd64.tar.gz"
      sha256 "63f49b11d405e52e69a1a1b39d6e0a5de272eab575834db67d3ecb3bff086eaa"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/terbolous/metagraf/releases/download/v0.1.54/mg-0.1.54-linux-amd64.tar.gz"
      sha256 "7adbecb63c9ca775f4dd222d0f3f7860865d767715630aad61d7717878f9f0bc"
    end
  end

  def install
    bin.install "mg"
  end
end
